### ISSUE TITLE
Build for CH32X035 on Fedora / gcc 14 without build-id section

### ISSUE THREAD

**Issue by frank-zago** [wagiminator/Development-Boards#7]
First, thanks for that nice framework for all these chips.

After installing the gcc riscv4 compiler, none of the examples would work. After investigating, I noticed that gcc put the build id section at the start of the firmware. I had to add "-Wl,...,--build-id=none" on the linker flags for the section to not be emitted, and examples started to work. That feature may be a default for that version of gcc now, so eventually people may see that issue ???

Old SO entry for that issue, with a couple more solutions: https://stackoverflow.com/questions/15316384/do-not-pass-build-id-to-linker-from-gcc

**Comment by wagiminator** [comment]
Thank you for the hint! I am currently traveling and therefore cannot test if the compiler flag causes any issues for me. Once I am back home next week, I will try it out and possibly make the flag the default.
